### ISSUE TITLE
i cant move sharkle 

### ISSUE THREAD

**Issue by R4p1ds** [LogicWrite/sharkie-meter#1]
the description says to press ctrl but it wont move

**Comment by IgPugliese** [comment]
Ah that's a shame, try clicking over the black lines when trying to move
sharkie!

**Comment by R4p1ds** [comment]
i d but it just pastes the idle animation onto my desktop

**Comment by IgPugliese** [comment]
Ah yes, try pressing down ctrl before clicking

**Comment by R4p1ds** [comment]
thanks this helped
